# Generated by Django 3.2 on 2021-05-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FD', 'Food Of The day'), ('M', 'MO:MO'), ('P', 'Pizza'), ('PD', 'Popular delight')], max_length=2),
        ),
    ]
