# Generated by Django 3.2 on 2021-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FD', 'Food Of The day'), ('M', 'MO:MO'), ('P', 'Pizza'), ('PF', 'Popular foods')], max_length=2),
        ),
    ]
